#include "usb.h"

#define USB_DEVICE DEVICE_DT_GET(DT_NODELABEL(zephyr_udc0))

// /* Get CDC-ACM UART device from devicetree */
// #define CDC_ACM_DEVICE DEVICE_DT_GET(DT_NODELABEL(cdc_acm_uart))
#define HID_DEVICE DEVICE_DT_GET(DT_NODELABEL(hid0))

// const struct device *cdc_dev = CDC_ACM_DEVICE;
const struct device *hid_dev = HID_DEVICE;

// /* USB device context with MCHP VID and cdc_com_port_single demo PID  */
// USBD_DEVICE_DEFINE(usbd_ctx,
//                    USB_DEVICE,
//                    0x04D8, 0x000A);  

/* USB device context with MCHP VID and hid_basic demo PID  */
USBD_DEVICE_DEFINE(usbd_ctx,
                   USB_DEVICE,
                   0x04D8, 0x003F);

USBD_DESC_LANG_DEFINE(lang_desc);
USBD_DESC_MANUFACTURER_DEFINE(mfr_desc, "Microchip Technology Inc.");
// USBD_DESC_PRODUCT_DEFINE(prod_desc, "Zephyr CDC-ACM");
USBD_DESC_PRODUCT_DEFINE(prod_desc, "Zephyr vendor HID");
USBD_DESC_SERIAL_NUMBER_DEFINE(sn_desc);

USBD_DESC_CONFIG_DEFINE(fs_cfg_desc, "FS Configuration");

USBD_CONFIGURATION_DEFINE(fs_config,
                          USB_SCD_SELF_POWERED,
                          250,  /* 500mA */
                          &fs_cfg_desc);

/* USB message Callback */
static void usb_msg_callback(struct usbd_context *const usbd_ctx,
		   					 const struct usbd_msg *const msg)
{
	if (usbd_can_detect_vbus(usbd_ctx)) {
		if (msg->type == USBD_MSG_VBUS_READY) {
			if (usbd_enable(usbd_ctx)) {
				/* Error */
			}
		}

		if (msg->type == USBD_MSG_VBUS_REMOVED) {
			if (usbd_disable(usbd_ctx)) {
				/* Error */
			}
		}
	}

	if (msg->type == USBD_MSG_CONFIGURATION) {
		/* Device changed configuration */
	}

   	// if (msg->type == USBD_MSG_CDC_ACM_CONTROL_LINE_STATE) {
    //     /* CDC ACM Line State update */
	// }

    // if (msg->type == USBD_MSG_CDC_ACM_LINE_CODING) {
    //     /* CDC ACM Line Coding update */
    // }
}

// Code generated by MCHP Chatbot
// PROMT: complete the HID report descriptor for a vendor hid report of 64 elements of 1 byte each used for send and receive data
static const uint8_t hid_report_desc[] = {
    0x06, 0x00, 0xFF,        // USAGE_PAGE (Vendor Defined)
    0x09, 0x01,              // USAGE (Vendor Usage 1)
    0xA1, 0x01,              // COLLECTION (Application)
    // OUT Report (Host to Device)
    0x09, 0x02,              //   USAGE (Vendor Usage 2)
    0x15, 0x00,              //   LOGICAL_MINIMUM (0)
    0x26, 0xFF, 0x00,        //   LOGICAL_MAXIMUM (255)
    0x75, 0x08,              //   REPORT_SIZE (8 bits)
    0x95, 0x40,              //   REPORT_COUNT (64 bytes)
    0x91, 0x02,              //   OUTPUT (Data,Var,Abs)
    // IN Report (Device to Host)
    0x09, 0x03,              //   USAGE (Vendor Usage 3)
    0x15, 0x00,              //   LOGICAL_MINIMUM (0)
    0x26, 0xFF, 0x00,        //   LOGICAL_MAXIMUM (255)
    0x75, 0x08,              //   REPORT_SIZE (8 bits)
    0x95, 0x40,              //   REPORT_COUNT (64 bytes)
    0x81, 0x02,              //   INPUT (Data,Var,Abs)
    0xC0                     // END_COLLECTION
};

/* HID device operations struct */
static const struct hid_device_ops hid_ops = {
	.get_report = hid_get_report_cb,
	.set_report = hid_set_report_cb,
    .input_report_done = hid_input_report_done_cb,
    .output_report = hid_output_report_cb,
};

int init_usb_device(void)
{
    int err;

    /* Adding Sting Descriptors */
	err = usbd_add_descriptor(&usbd_ctx, &lang_desc);
	if (err) {
		return err;
	}

	err = usbd_add_descriptor(&usbd_ctx, &mfr_desc);
	if (err) {
		return err;
	}

	err = usbd_add_descriptor(&usbd_ctx, &prod_desc);
	if (err) {
		return err;
	}

	err = usbd_add_descriptor(&usbd_ctx, &sn_desc);
	if (err) {
		return err;
	}

  	/* Adding Full-Speed configuration */
    err = usbd_add_configuration(&usbd_ctx, USBD_SPEED_FS, &fs_config);
	if (err) {
		return err;
	}

    // /* Registering the CDC-ACM class */
    // err = usbd_register_class(&usbd_ctx, "cdc_acm_0", USBD_SPEED_FS, 1);
    // if (err) {
    //     return err;
    // }
    
    /* Registering the HID class */
    err = usbd_register_class(&usbd_ctx, "hid_0", USBD_SPEED_FS, 1);
    if (err) {
        return err;
    }

    err = hid_device_register(hid_dev,
                             hid_report_desc,
                             sizeof(hid_report_desc),
                             &hid_ops);
    if (err != 0) {
        return err;
    }

    usbd_device_set_code_triple(&usbd_ctx, USBD_SPEED_FS, 0, 0, 0);

	/* Registering USB message callback */
    err = usbd_msg_register_cb(&usbd_ctx, usb_msg_callback);
	if (err) {
		return err;
	}

  	/* Ititialize the USB device */
    err = usbd_init(&usbd_ctx);
	if (err) {
		return err;
	}

	/* If the controller doesnt support VBUS detection, enable it immediately */
    if (!usbd_can_detect_vbus(&usbd_ctx)) {
		err = usbd_enable(&usbd_ctx);
		if (err) {
			printk("Failed to enable device support\r\n");
			return err;
		}
	}

    return err;
}
